export const SET_ALL_CONTINENTS = 'SET_ALL_CONTINENTS'
export const SET_ALL_COUNTRIES_BY_CONTINENT = 'SET_ALL_COUNTRIES_BY_CONTINENT'
export const ERROR = 'ERROR'
export const DATA_LOADING = 'DATA_LOADING'