export const SET_ALL_CONTINENTS = 'SET_ALL_CONTINENTS'
export const SET_ALL_COUNTRIES_BY_CONTINENT = 'SET_ALL_COUNTRIES_BY_CONTINENT'
export const ERROR = 'ERROR'
export const DATA_LOADING = 'DATA_LOADING'


export const SWITCH_DATA_TYPE = 'SWITCH_DATA_TYPE'

export const SET_GLOBAL_PARAMS = 'SET_GLOBAL_PARAMS'
export const RESET_GLOBAL_PARAMS = 'RESET_GLOBAL_PARAMS'